# File              : action.yaml
# Author            : Alexandre Saison <alexandre.saison@inarix.com>
# Date              : 28.05.2021
# Last Modified Date: 05.07.2021
# Last Modified By  : Alexandre Saison <alexandre.saison@inarix.com>
name: 'ga-create-pull-request'
description: 'Create a pullRequest'
inputs:
  repo:
    description: 'generated modelInstanceId given by previous registerModel in bookish-happiness'
    required: true
  base:
    description: 'Host of the Argo server to trigger the worflow'
    required: false
    default: 'argo.inarix.com'
  head:
    description: 'Name of the Argo Workflow template to run'
    required: false
    default: 'workflowtemplate/wt-model-deploy-non-regression'
outputs:
  pullNumber: # id of output
    description: 'Created PullRequest number identifier'
runs:
  using: 'docker'
  image: 'Dockerfile'
