# File              : action.yaml
# Author            : Alexandre Saison <alexandre.saison@inarix.com>
# Date              : 28.05.2021
# Last Modified Date: 05.07.2021
# Last Modified By  : Alexandre Saison <alexandre.saison@inarix.com>
name: 'ga-create-pull-request'
description: 'Create a pullRequest'
inputs:
  repo:
    description: 'name of the repository'
    required: true
  base:
    description: 'Destination branch to create pull request'
    required: false
    default: 'master'
  head:
    description: 'Source branch to create pull request'
    required: true
outputs:
  pullNumber: # id of output
    description: 'Created PullRequest number identifier'
runs:
  using: 'docker'
  image: 'Dockerfile'
